// forge/lib/blocktrails.js — pure crypto extracted from plugin.js (no forge
// state): bech32 / bech32m encoders (npub + P2TR address) and the Blocktrails
// chained BIP-341 TapTweak trail math. Pure functions over node:crypto +
// @noble/curves. plugin.js re-exports markStateHash / npubEncode / trailAddress
// / trailProgram from here so the test imports stay unchanged.
import crypto from 'node:crypto';
import { secp256k1 } from '@noble/curves/secp256k1';

// bech32 (BIP-173, full checksum — no shortcuts) npub encoder, pure node.
// Unit-tested against the canonical NIP-19 vector in test.js. Tier 3.5
// generalizes the same polymod into a bech32m (BIP-350) P2TR address
// encoder — the two specs differ ONLY by the checksum constant
// (bech32 xors 1, bech32m xors 0x2bc830a3).
const BECH32_CHARSET = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';
const BECH32M_CONST = 0x2bc830a3;

function bech32Polymod(values) {
  const GEN = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];
  let chk = 1;
  for (const v of values) {
    const top = chk >>> 25;
    chk = ((chk & 0x1ffffff) << 5) ^ v;
    for (let i = 0; i < 5; i++) if ((top >>> i) & 1) chk ^= GEN[i];
  }
  return chk;
}

/** 8-bit bytes regrouped big-endian into 5-bit words (padded). */
function to5bit(bytes) {
  const words = [];
  let acc = 0;
  let bits = 0;
  for (const b of bytes) {
    acc = (acc << 8) | b;
    bits += 8;
    while (bits >= 5) { bits -= 5; words.push((acc >>> bits) & 31); }
  }
  if (bits) words.push((acc << (5 - bits)) & 31);
  return words;
}

/** hrp + data words + 6-word checksum (constant picks bech32 vs bech32m). */
function bech32Assemble(hrp, words, constant) {
  const expanded = [...hrp].map((c) => c.charCodeAt(0) >>> 5)
    .concat([0], [...hrp].map((c) => c.charCodeAt(0) & 31));
  const poly = bech32Polymod([...expanded, ...words, 0, 0, 0, 0, 0, 0]) ^ constant;
  const checksum = Array.from({ length: 6 }, (_, i) => (poly >>> (5 * (5 - i))) & 31);
  return `${hrp}1${[...words, ...checksum].map((d) => BECH32_CHARSET[d]).join('')}`;
}

/** 64-hex pubkey -> npub1... (NIP-19). Exported for the vector test. */
export function npubEncode(hex) {
  return bech32Assemble('npub', to5bit(Buffer.from(hex, 'hex')), 1);
}

/** 32-byte P2TR witness program -> bech32m address (BIP-350, version 1). */
export function p2trAddressEncode(hrp, program) {
  return bech32Assemble(hrp, [1, ...to5bit(program)], BECH32M_CONST);
}

// ------------------------------------------- Blocktrails trail math (3.5)
// Implemented FROM THE SPEC (blocktrails spec v0.2 — the mirror at
// blocktrails/spec/spec.md is normative): chained BIP-341 TapTweak.
//
//   h  = sha256(serialize(state))                       state hash
//   tᵢ = tagged_hash("TapTweak", x_only(Pᵢ₋₁) || h) mod n
//   Pᵢ = Pᵢ₋₁ + tᵢ·G                                    full point kept
//   output = x_only(Pᵢ)  →  bech32m (tb1p…)             x-only at the boundary
//
// serialize(state) is the git-mark-demo convention:
// JSON.stringify({ commit, repo, branch }) — canonical because the object
// is built literally in that key order everywhere it is hashed.
// Parity note (a Finding): the spec keeps FULL points through the chain
// and takes x_only only at the output boundary — x(P) == x(-P) makes the
// output comparison parity-free, and the tweak input is the raw
// x-coordinate of the (possibly odd-Y) running point, NOT a re-lifted
// even-Y key as in BIP-341 wallet derivation. Cross-checked in test.js
// against a vector generated by the maintainer's reference implementation.
// The blocktrails npm package is deliberately not imported (spec cited,
// math local); @noble/curves does the point arithmetic.

const SECP_N = secp256k1.CURVE.n;
const sha256Of = (...parts) => {
  const h = crypto.createHash('sha256');
  for (const p of parts) h.update(p);
  return h.digest();
};
const TAPTWEAK_TAG = sha256Of(Buffer.from('TapTweak', 'utf8'));

/** Canonical mark state hash: sha256 hex of the state JSON. Exported for tests. */
export function markStateHash(state) {
  return crypto.createHash('sha256').update(JSON.stringify(state), 'utf8').digest('hex');
}

/** BIP-341 TapTweak scalar over (x_only(P), stateHash), in [1, n-1]. */
function tapTweakScalar(xOnly, stateHashBytes) {
  const t = BigInt(`0x${sha256Of(TAPTWEAK_TAG, TAPTWEAK_TAG, xOnly, stateHashBytes).toString('hex')}`) % SECP_N;
  // The spec REQUIRES rejecting t = 0 (probability ~2^-256).
  if (t === 0n) throw new Error('blocktrails: TapTweak scalar is zero — state rejected');
  return t;
}

/** Chain the tweaks: base pubkey + one TapTweak per state hash (hex list). */
function trailPoint(pubkeyBaseHex, stateHashes) {
  let P = secp256k1.ProjectivePoint.fromHex(pubkeyBaseHex);
  for (const h of stateHashes) {
    const xOnly = P.toRawBytes(true).subarray(1); // raw x of the running point
    const t = tapTweakScalar(xOnly, Buffer.from(h, 'hex'));
    P = P.add(secp256k1.ProjectivePoint.BASE.multiply(t));
  }
  return P;
}

/** Witness program (x-only, 64-hex) after chaining stateHashes. Exported for tests. */
export function trailProgram(pubkeyBaseHex, stateHashes) {
  return Buffer.from(trailPoint(pubkeyBaseHex, stateHashes).toRawBytes(true).subarray(1)).toString('hex');
}

/** Derived P2TR address after chaining stateHashes. Exported for tests. */
export function trailAddress(pubkeyBaseHex, stateHashes, hrp) {
  return p2trAddressEncode(hrp, Buffer.from(trailProgram(pubkeyBaseHex, stateHashes), 'hex'));
}

/** Shortened npub for UI rendering: npub1abcd…wxyz. */
export function npubShort(hex) {
  const npub = npubEncode(hex);
  return `${npub.slice(0, 9)}…${npub.slice(-4)}`;
}
